spring:
  application:
    name: demo-kafka-producer-java21
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic:  book-events
    topic2: user-events
    template:
      default-topic: book-events
    producer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9091,localhost:9092,localhost:9093